- 
  name: Configure Docker Engine
  hosts: rl_base_node
  vars:
    lab_git_url: "https://github.com/cs-pub-ro/RL-linux-labs.git"
    lab_path: "{{ lookup('env', 'LABS_DEST') | default('/opt/rl-labs', True) }}"
    vm_debug: "{{ lookup('env', 'VM_DEBUG') }}"
  tasks:
    # - name: Disable network abstractization and enable IPv6
    #   copy:
    #     dest: "/etc/docker/daemon.json"
    #     content: |
    #       {
    #         "iptables":false,
    #         "bridge":"none",
    #         "ip-forward":false,
    #         "ipv6":true
    #       }

    - name: Add 'update' git remote to rl-labs
      shell: git remote add update "{{ lab_git_url }}"; git remote remove origin
      args:
        chdir: "{{ lab_path }}"

    - name: Run the rl-labs build script
      command: "{{ lab_path }}/build.sh" 

    # - name: Set the update required flag
    #   command: "touch {{ lab_path }}/.update-required" 
    #   when: "(vm_debug == '') or (vm_debug == '0')"

    # manual: ansible-galaxy collection install community.general.docker_image
    # - name: Build RL Lab Docker Image
    #   community.general.docker_image:
    #     name: rlbase:latest
    #     build:
    #       path: "{{lab_path}}"
    #       dockerfile: Dockerfile.base
    #       network: host
    #       pull: yes
    #     source: build

    # We don't do that here
    #- name: Reboot the machine (scheduled in 1 minute)
    #  shell: shutdown -r +1
    #  reboot: 
