#!/usr/bin/env zsh

# install Zsh Plugin Manager
source ~/.config/zsh/zpm/zpm.zsh 2>/dev/null || {
  git clone https://github.com/zpm-zsh/zpm ~/.config/zsh/zpm
  source ~/.config/zsh/zpm
}

### Tmux
export TMUX_AUTOSTART=false
# zpm if ssh load zpm-zsh/tmux
# zpm if-not ssh load zpm-zsh/tmux,apply:path

### VTE
zpm if vte load zpm-zsh/vte

## Spaceship theme
export SPACESHIP_ROOT="$HOME/.config/zsh/spaceship"
if [[ ! -f "$SPACESHIP_ROOT/spaceship.zsh" ]]; then
	git clone --depth=1 "https://github.com/spaceship-prompt/spaceship-prompt.git" "$SPACESHIP_ROOT"
fi
source "$SPACESHIP_ROOT/spaceship.zsh"

### 3party plugins
zpm load                      \
  zpm-zsh/core-config         \
  zpm-zsh/ignored-users,async \
  zpm-zsh/check-deps,async    \
  zpm-zsh/ls,async            \
  zpm-zsh/colorize,async      \
  zpm-zsh/ssh,async           \
  zpm-zsh/dot,async           \
  zpm-zsh/undollar,async      \
  zpm-zsh/bookmarks,async     \
  voronkovich/gitignore.plugin.zsh,async     \
  zpm-zsh/autoenv,async                      \
  mdumitru/fancy-ctrl-z,async                \
  zpm-zsh/zsh-history-substring-search,async \
  zsh-users/zsh-autosuggestions,async        \
  zpm-zsh/fast-syntax-highlighting,async     \
  zpm-zsh/history-search-multi-word,async

source ~/.zshrc.local 2>/dev/null

